name: Dependabot Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # boto3 and friends: all update types
  auto-approve-specific:
    permissions:
      contents: write
      pull-requests: write
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@bbe97497e09b0f728446f9f3a93daa897e2d64a1
    with:
      accept_packages: 'oci'
      allowed_update_types: 'minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}

  # test requirements: any update type, filtered by path
  auto-approve-test-reqs:
    permissions:
      contents: write
      pull-requests: write
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@bbe97497e09b0f728446f9f3a93daa897e2d64a1
    with:
      file_pattern: 'tests/**'
      allowed_update_types: 'major,minor,patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}

  # everything else: patch only
  auto-approve-patch:
    permissions:
      contents: write
      pull-requests: write
    uses: tnoff/github-workflows/.github/workflows/dependabot-auto-approve.yml@bbe97497e09b0f728446f9f3a93daa897e2d64a1
    with:
      allowed_update_types: 'patch'
    secrets:
      bot_token: ${{ secrets.APPROVAL_BOT_PAT }}